### ISSUE TITLE
There should be widget area over & blew the <main>

### ISSUE THREAD

**Issue by sohailsarwar101** [Manoz/split-me#3]
There should be widget area over & blew the main side
Like:
____widget area____
-------main area--------
____ 1 widget _____
_2 Colman widgets_
_3 Colman widgets_

Thanks

**Comment by Manoz** [comment]
Hi and thx but I didn't want to integrate widgets on this theme. It is a very considered choice. I'm preparing a big update so maybe I'll add a clean widget area in the next version :)

**Comment by sohailsarwar101** [comment]
Good to hear about upcoming update :) any milestone for this update?
I like to suggest a look at heydesigner.com design. Hopefully you will get a bit of idea for more...
oh one thing more! There should be a search form anywhere you like.

Thanks,
Sohail Sarwar.

**Comment by Manoz** [comment]
Actually, my theme has a 40% left column and the main content is 60% wide. I want to add more visibility and readability to the content so I'll improve a bit the main content column and I will improve the font size too.

I also want to add more things like a social media links nav bar and of course a search form in the right column.

heydesigner.com is a great exemple, thank you :)

**Comment by sohailsarwar101** [comment]
OK! So, I'm sitting here and wait for update.

**Comment by Manoz** [comment]
The update is already pushed on Github but still in review on WordPress :) https://themes.trac.wordpress.org/ticket/21178

No widgets area since I don't know where to place it. I'm working on a new 2 columns theme like Split Me but with better features.

**Comment by sohailsarwar101** [comment]
Ok........ fine, update is not as much bigger as i'm expecting...
At all Split Me is a very nice theme.
Good Luck for future!

**Comment by Manoz** [comment]
Yes that's the problem with Split Me. It was my very first theme on WordPress directories and today I don't know how to improve it now. I wanted a very simple theme without much options and I think my goal is achieved with Split Me. That's why I'm working on a new similar theme. Thx for all your tips by the way :)
